
  CREATE TABLE "R3BELANET"."USERS" 
   (	"ID" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 BYTE), 
	"VISIBILITY" VARCHAR2(255 BYTE), 
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "R3"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "R3" ;
 

  CREATE OR REPLACE TRIGGER "R3BELANET"."USERS_TRG" 
BEFORE INSERT ON USERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT USERS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "R3BELANET"."USERS_TRG" ENABLE;
 
